name: Bug Report
description: Report a reproducible bug or problem in MagicLottie.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the details below to help us reproduce and fix the issue.

  - type: input
    id: summary
    attributes:
      label: Short summary
      description: Briefly summarize the problem
      placeholder: "Animation does not render after import"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: "What steps cause the problem? (if possible, attach a sample file)"
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: "The animation should show a preview after loading."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: "Nothing happens, or error in console."
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser / Device
      placeholder: "e.g. Chrome 123, Android 14, iPhone 15"
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Any other info, screenshots, or links?
